# %%
"""Template Finder [Shared Starter Code] (Psy)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AdGWtNuz570CnNALl8gMC9MJU9Xnlffn
"""

import os
import pickle

import matplotlib.pyplot as plt
import numpy as np
import tqdm.auto as tqdm
from xgboost import XGBClassifier
import mydatasets.common

# %%
"""## Data"""

# file = open('/content/drive/My Drive/Data/cube_20_0.3.pkl', 'rb')
# unpickled_data = pickle.load(file)
# file.close()

# Xtrn, Ytrn = unpickled_data['train']
# muX = 0.0  # np.mean(Xtrn, 0, keepdims=True)
# stdX = 1.0  # np.std(Xtrn, 0, keepdims=True)
# Xtrn = (Xtrn-muX)/stdX
# Ntrn, d = Xtrn.shape
# nclasses = 8
# Ytrn = np.int32(Ytrn)

# Xval, Yval = unpickled_data['valid']
# Xval = (Xval-muX)/stdX
# Yval = np.int32(Yval)

# Xtst, Ytst = unpickled_data['test']
# Xtst = (Xtst-muX)/stdX
# Ytst = np.int32(Ytst)

# nclass = 8
# d = 20
# eye_nclass = np.eye(nclass, dtype=np.float32)
# Ytrn_onehot = np.concatenate([eye_nclass[np.int64(y), None, :] for y in Ytrn], 0)

# file = open("/content/drive/My Drive/Data/psy/big5_C_cls.pkl", "rb")
# unpickled_data = pickle.load(file)
# file.close()

# %%
data_p = os.path.join(
    mydatasets.common.get_datasets_files_root_dir(), "aaco", "big5_C_cls.pkl"
)
with open(data_p, "rb") as file:
    unpickled_data = pickle.load(file)

# %%
Xtrn: np.ndarray
Ytrn: np.ndarray
Xtrn, Ytrn = unpickled_data["train"]
# muX = np.mean(Xtrn, 0, keepdims=True)
# stdX = np.std(Xtrn, 0, keepdims=True)
# Xtrn = (Xtrn-muX)/stdX
Xtrn = Xtrn.astype(dtype=np.float32)
Ntrn, d = Xtrn.shape
nclass = 4
Ytrn = Ytrn.astype(dtype=np.int64)

Xval: np.ndarray
Yval: np.ndarray
Xval, Yval = unpickled_data["valid"]
# Xval = (Xval-muX)/stdX
Xval = Xval.astype(dtype=np.float32)
Yval = Yval.astype(dtype=np.int64)

Xtst: np.ndarray
Ytst: np.ndarray
Xtst, Ytst = unpickled_data["test"]
Xtst = Xtst.astype(dtype=np.float32)
# Xtst = (Xtst-muX)/stdX
Ytst = Ytst.astype(dtype=np.int64)

# %%
nclasses = nclass
eye_nclass: np.ndarray = np.eye(nclass, dtype=np.float32)
Ytrn_onehot: np.ndarray = np.concatenate(
    [eye_nclass[np.int64(y), None, :] for y in Ytrn], 0
)

# %%
"""## Code

Let's begin by looking for templates that we can use to guide AFA. In much of what we'll consider below, we need a classifier $\hat{y}(x_o)$ that can predict with arbitrary given features. We'll use an *ensemble* (with random subsets of instances) of masked classifiers that operate over $(x\cdot b, b)$ since these ensembles: 1) do a good job of estimating uncertainties; 2) make it easy to evaluate points on estimators that did not see them during training.

This helper function returns an ensemble and filter indicators (to indicate what classifiers did not see specific training points).
"""


def train_classifiers(
    Xtrn: np.ndarray,
    Ytrn: np.ndarray,
    n_ensembles=64,
    mask_generator=None,
    masksper=4,
    n_estimators=40,
):
    """
    Train an ensemble of masked classifiers on tuples of inputs and masks.
    Args:
      Xtrn: N x d inputs
      Ytrn: N array of labels
      n_ensembles: int number of estimators
      mask_generator: function that takes in number of random masks to generate.
        If None, then Bernoulli masks are used
      masksper: int number of masks to generate per instance to train each
        classifier
      n_estimators: XGB n_estimators parameter to use for base models
    Returns:
      classifiers: list of n_ensembles classifiers
      filters: N x n_ensembles array of indicators of which classifiers to use for
        instances (indicating that a classifier was *not* trained on the
        respective instance)
    """

    classifiers = []
    splits_rand = []
    N_tot = Xtrn.shape[0]

    d = Xtrn.shape[1]
    pbar = tqdm.trange(n_ensembles, desc="random split", dynamic_ncols=True, leave=True)
    for vi in pbar:
        # Get random split
        in_range = np.random.rand(N_tot) <= 0.5
        splits_rand.append(in_range)
        X_class = Xtrn[in_range]
        Y_class = Ytrn[in_range]
        # Make masks
        X_class = np.concatenate([X_class] * masksper, 0)
        Y_class = np.concatenate([Y_class] * masksper, 0)
        if mask_generator is None:
            B = np.concatenate(
                [
                    np.sum(
                        np.random.permutation(np.eye(d))[:, : np.random.randint(d)],
                        1,
                        keepdims=True,
                    )
                    for _ in range(X_class.shape[0])
                ],
                1,
            )
            B = np.float32(B.T)
        else:
            B = mask_generator(X_class.shape[0])
        X_class = np.concatenate((X_class * B, B), 1)
        # Train classifier
        est = XGBClassifier(n_estimators=n_estimators)
        est.fit(X_class, Y_class)
        classifiers.append(est)
    pbar.close()

    return classifiers, np.logical_not(np.stack(splits_rand, -1))


# %%
# train initial classifier
init_classifiers: list[XGBClassifier]
# init_filters[i, :] is a mask to indicate instances that are NOT used in i^th model in ensemble
# (n, n_ensemble)
init_filters: np.ndarray
init_classifiers, init_filters = train_classifiers(
    Xtrn, Ytrn, n_ensembles=64, masksper=4, n_estimators=40
)

# %%
"""Since we need to begin with *an* acquisition, all templates should share a common feature.

There are several potential ways of estimating what this starting feature should be. Here, I propose using the [ACO cost objective](https://proceedings.mlr.press/v235/valancius24a.html):
$\arg\min_{v \subseteq \{1, \dots, d\} \setminus o} \mathbb{E}_{\mathbf{y}, \mathbf{x}_v \mid {x}_o} \left[ \ell \left( \hat{y}({x}_o, \mathbf{x}_v), \mathbf{y} \right) \right] + \alpha c(v; o)$ for the special case where $o = \emptyset$; i.e. $\arg\min_{v \subseteq \{1, \dots, d\} } \mathbb{E}_{\mathbf{y}, \mathbf{x}_v} \left[ \ell \left( \hat{y}(\mathbf{x}_v), \mathbf{y} \right) \right] + \alpha c(v)$, which is equivalent to a static feature selection type loss. Note that this will return an entire subset $v \subseteq [\![d]\!]$. We can perform multiple trials to select a single feature (e.g., based on stability of selection).

`estimate_start` is a helper function to estimate the above cost objective by keeping track of the lowest mask cost objective that each feature appears in (i.e. the total loss of the best mask that contains each feature).
`estimate_start` is meant to consider relatively few masks and bigger batch sizes for estimating average NLL. `estimate_start_minitrials` considers more masks and smaller batches instead, which can be useful for further tie-breaks.
"""


def estimate_start(
    Xtrn, Ytrn, classifier_filters, classifiers, featcost, ntrials=500, trl_bsize=5000
):
    """
    Estimate the lowest mask cost objective that each feature appears in (i.e.
    the cost objective of the best mask that contains each feature).
    Args:
      Xtrn: N x d inputs
      Ytrn: N array of labels
      classifier_filters: N x nests array of indicators of which classifiers to
        use for instances
      classifiers: list of nests classifiers
      featcost: alpha penalty multiplier to l1-norm of masks
      ntrials: number of maskes to consider
      trl_bsize: batch size for to estimate average NLL for each mask
    Returns:
      startdim: a feature in the lowest cost objective mask
      bestmask: d len array of lowest cost objective of the best mask
        that contains each feature
    """
    mval = 1e8
    bestmask = 1e8 * np.ones((d,), dtype=np.float32)
    # random feature masks
    # (ntrials, n_covs)
    B = (
        np.concatenate(
            [
                np.sum(
                    np.random.permutation(np.eye(d))[:, : np.random.randint(d)],
                    1,
                    keepdims=True,
                )
                for _ in range(ntrials)
            ],
            1,
        )
        .astype(np.float32)
        .T
    )
    for trl in range(ntrials):
        print(trl, np.min(bestmask), np.argmin(bestmask))
        rprm = np.random.permutation(Xtrn.shape[0])[:trl_bsize]
        Btrl = np.tile(B[trl, None, :], (len(rprm), 1))
        XBtrl = np.concatenate((Xtrn[rprm] * Btrl, Btrl), 1)
        preds = np.stack([est.predict_proba(XBtrl) for est in classifiers], -1)
        if classifier_filters is None:
            preds = np.mean(preds, -1)
        else:
            nests = np.sum(classifier_filters[rprm], -1, keepdims=True)
            preds = np.sum(preds * classifier_filters[rprm, None, :], -1) / nests

        nlls = np.stack([-np.log(preds[i, y]) for i, y in enumerate(Ytrn[rprm])], 0)
        crit = np.mean(nlls) + featcost * np.sum(B[trl])
        bestmask = np.minimum(bestmask, crit * B[trl] + mval * (1.0 - B[trl]))
    return np.argmin(bestmask), bestmask


# %%
# config
featcost = 0.075

_, bestmask1 = estimate_start(Xtrn, Ytrn, init_filters, init_classifiers, featcost)
_, bestmask2 = estimate_start(Xtrn, Ytrn, init_filters, init_classifiers, featcost)
bestmask = 0.5 * (bestmask1 + bestmask2)
print(bestmask)


# %%
def eval_masks(
    X, B, classifiers, Y=None, bsize=16, matched_B=False, classifier_filters=None
):
    """
    Evaluate an ensemble of classifiers on tuples of inputs and masks.
    Args:
      X: N x d data matrix
      B: M x d mask matrix
      Y: N array of labels. If Y is given then the negative log likelihoods
        is returned else predictions are returned.
      If matched_B is True then N==M and instances are only evaluated on
        respective masks; else (default), all instances are evaluated on each
        mask in B.
      classifier_filter: N x nests matrix of indicators of which classifiers to
        use for instances
    Returns: N x M nlls if Y is given else N x M x nclasses predictions (when
      matched_B=False).
    """
    N = X.shape[0]
    M = B.shape[0]

    if Y is not None:
        if matched_B:
            out = np.zeros((N,), np.float32)
        else:
            out = np.zeros((N, M), np.float32)
    else:
        if matched_B:
            out = np.zeros((N, classifiers[0].n_classes_), np.float32)
        else:
            out = np.zeros((N, M, classifiers[0].n_classes_), np.float32)
    for bi in range(0, N, bsize):
        Xbatch = X[bi : bi + bsize]
        Ybatch = Y[bi : bi + bsize]
        if matched_B:
            Bbatch = B[bi : bi + bsize]
        else:
            Bbatch = np.tile(B, (Xbatch.shape[0], 1))
            Xbatch = np.repeat(Xbatch, M, 0)

        Xbatch = np.concatenate((Xbatch * Bbatch, Bbatch), 1)
        preds = np.stack([est.predict_proba(Xbatch) for est in classifiers], -1)
        if classifier_filters is None:
            preds = np.mean(preds, -1)
        else:
            split_batch = classifier_filters[bi : bi + bsize]
            split_batch = np.repeat(split_batch, M, 0)
            nests = np.sum(split_batch, -1, keepdims=True)
            preds = np.sum(preds * split_batch[:, None, :], -1) / nests
        if not matched_B:
            preds = preds.reshape(-1, M, classifiers[0].n_classes_)
        if Y is None:
            out[bi : bi + bsize, ...] = preds
        else:
            out[bi : bi + bsize, ...] = np.stack(
                [-np.log(preds[i, ..., y]) for i, y in enumerate(Ybatch)], 0
            )
    return out


def estimate_start_minitrials(
    Xtrn, Ytrn, classifier_filters, classifiers, featcost, ntrials=32, trl_bsize=64
):
    bestmask = np.zeros((d,), dtype=np.float32)

    for trl in range(ntrials):
        print(trl)
        rprm = np.random.permutation(Xtrn.shape[0])[:trl_bsize]
        B = np.concatenate(
            [
                np.sum(
                    np.random.permutation(np.eye(d))[:, : np.random.randint(d)],
                    1,
                    keepdims=True,
                )
                for _ in range(5000)
            ],
            1,
        )
        B = np.float32(B.T)
        nlls = eval_masks(
            Xtrn[rprm],
            B,
            classifiers,
            Y=Ytrn[rprm],
            classifier_filters=classifier_filters[rprm],
        )
        crit = np.mean(nlls, 0) + featcost * np.sum(B, 1)
        trlbest = B[np.argmin(crit), :]
        print(trlbest)
        bestmask = bestmask + trlbest
    return np.argmax(bestmask), bestmask


# %%
# tie-break if needed
if np.sum(np.equal(bestmask, np.min(bestmask))) > 1:
    print("tie!")
    _, bestmask_tiebreak = estimate_start_minitrials(
        Xtrn, Ytrn, init_filters, init_classifiers, featcost
    )
    startdim = np.argmax(bestmask_tiebreak * np.equal(bestmask, np.min(bestmask)))
    plt.plot(bestmask_tiebreak * np.equal(bestmask, np.min(bestmask)))
else:
    startdim = np.argmin(bestmask)
    plt.plot(bestmask)

print(startdim)

# %%
"""Now that we have the common feature (the starting feature in AFA), we can look for our 'templates'.

Since the space of potential masks is huge, $2^d$, it's prudent to precompute and cache mask cost objectives on a set of potential mask candidates. `eval_masks` and `get_mask_losses` are helper functions to do so.
"""


def get_mask_losses(
    Xtrn, Ytrn, B, classifiers, featcost, bsize=256, classifier_filters=None
):
    # TODO: use filters?
    mask_costs = featcost * np.sum(B, 1)

    bsize = 256
    Xcosts = []
    pbar = tqdm.trange(
        0, Xtrn.shape[0], bsize, desc="mask loss", leave=True, dynamic_ncols=True
    )
    for si in pbar:
        nlls = eval_masks(
            Xtrn[si : si + bsize],
            B,
            classifiers,
            Y=Ytrn[si : si + bsize],
            classifier_filters=classifier_filters,
        )
        Xcosts.append(nlls + mask_costs)

    return np.concatenate(Xcosts, 0)


"""Let $\mathcal{M}$ be the universe of masks, and $c^{(i)}_j$ be the cost of the $j$th mask on the $i$th instance. We can then pose the template finding problem as finding  $$\hat{T} = \operatorname{argmin}\limits_{T \subset \mathcal{M},\, |T|=K} \frac{1}{N}\sum_{i=1}^N \min_{j\in T} c^{(i)}_j.$$

Clearly, one can employ a greedy strategy to add a single additional mask to a current template set $T$. I propose an adjusted cost approach to each greedy iteration for easy vectorization.
"""


def vanilla_greedy_cost_selection(costs, k, selected=None):
    # Start selected set with the mask that gives to lowest avg cost
    if selected is None:
        selected = [np.argmax(np.mean(costs, 0))]
    for i in range(1, k):
        # best possible cost for each instance with current set of masks
        selected_cost = np.min(costs[:, selected], -1, keepdims=True)
        print("{} {}".format(i, np.mean(selected_cost)))
        # potential improvement to each instances if respective mask were available
        adj_cost = np.minimum(costs - selected_cost, 0)  # measuring savings over best
        mean_adj_cost = np.mean(adj_cost, 0)
        if not np.any(mean_adj_cost < 0.0):
            return selected
        selected.append(np.argmin(mean_adj_cost))
    return selected


# %%
classifiers = init_classifiers
filters = init_filters
d = Xtrn.shape[1]
eyed = np.eye(d, dtype=np.float32)
estart = eyed[startdim]
# get candidate templates
ncand = 10000
B = np.concatenate(
    [
        np.sum(np.random.permutation(eyed)[:, : np.random.randint(d)], 1, keepdims=True)
        for _ in range(ncand)
    ],
    1,
)
B = np.float32(B.T)
B[:, startdim] = 1.0
mask_costs = featcost * np.sum(B, 1)
# subsample instances for speed
rprm = np.random.permutation(Xtrn.shape[0])[:6000]
Xrnd = Xtrn[rprm]
Yrnd = Ytrn[rprm]
Xcosts = get_mask_losses(
    Xrnd, Yrnd, B, classifiers, featcost, bsize=256, classifier_filters=filters
)

# %%
K_temp = 128
selected = vanilla_greedy_cost_selection(Xcosts, K_temp)
B_templates_vg = B[selected, :]

# %%
# evaluate on held out set
rprm = np.random.permutation(Xval.shape[0])[:1500]
Xrnd_val = Xval[rprm]
Yrnd_val = Yval[rprm]
Xcosts_val = get_mask_losses(
    Xrnd_val, Yrnd_val, B_templates_vg, classifiers, featcost, bsize=256
)
print(np.mean(np.min(Xcosts_val, -1)))

# %%
