# -*- coding: utf-8 -*-
"""Template Multi-round Finder and ACO Rollout [Share Starter Code] (alpha=.075, Psy)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_NXVRN7LlvZV8G_63yEROHxk-bmge71
"""
# %%
import os
import pickle

# %matplotlib inline
import matplotlib.pyplot as plt
import mydatasets.common
import numpy as np
from xgboost import XGBClassifier

"""## Data"""

# file = open('/content/drive/My Drive/Data/cube_20_0.3.pkl', 'rb')
# unpickled_data = pickle.load(file)
# file.close()

# Xtrn, Ytrn = unpickled_data['train']
# muX = 0.0  # np.mean(Xtrn, 0, keepdims=True)
# stdX = 1.0  # np.std(Xtrn, 0, keepdims=True)
# Xtrn = (Xtrn-muX)/stdX
# Ntrn, d = Xtrn.shape
# nclasses = 8
# Ytrn = np.int32(Ytrn)

# Xval, Yval = unpickled_data['valid']
# Xval = (Xval-muX)/stdX
# Yval = np.int32(Yval)

# Xtst, Ytst = unpickled_data['test']
# Xtst = (Xtst-muX)/stdX
# Ytst = np.int32(Ytst)

# nclass = 8
# d = 20
# eye_nclass = np.eye(nclass, dtype=np.float32)
# Ytrn_onehot = np.concatenate([eye_nclass[np.int64(y), None, :] for y in Ytrn], 0)

# %%
data_p = os.path.join(
    mydatasets.common.get_datasets_files_root_dir(), "aaco", "big5_C_cls.pkl"
)
with open(data_p, "rb") as file:
    unpickled_data = pickle.load(file)


# %%
Xtrn, Ytrn = unpickled_data["train"]
# muX = np.mean(Xtrn, 0, keepdims=True)
# stdX = np.std(Xtrn, 0, keepdims=True)
# Xtrn = (Xtrn-muX)/stdX
Xtrn = np.float32(Xtrn)
Ntrn, d = Xtrn.shape
nclass = 4
Ytrn = np.int32(Ytrn)

Xval, Yval = unpickled_data["valid"]
# Xval = (Xval-muX)/stdX
Xval = np.float32(Xval)
Yval = np.int32(Yval)

Xtst, Ytst = unpickled_data["test"]
Xtst = np.float32(Xtst)
# Xtst = (Xtst-muX)/stdX
Ytst = np.int32(Ytst)

nclasses = nclass
eye_nclass = np.eye(nclass, dtype=np.float32)
Ytrn_onehot = np.concatenate([eye_nclass[np.int64(y), None, :] for y in Ytrn], 0)

# %%
"""## Code

Let's begin by looking for templates that we can use to guide AFA. In much of what we'll consider below, we need a classifier $\hat{y}(x_o)$ that can predict with arbitrary given features. We'll use an *ensemble* (with random subsets of instances) of masked classifiers that operate over $(x\cdot b, b)$ since these ensembles: 1) do a good job of estimating uncertainties; 2) make it easy to evaluate points on estimators that did not see them during training.

This helper function returns an ensemble and filter indicators (to indicate what classifiers did not see specific training points).
"""


def train_classifiers(
    Xtrn, Ytrn, nests=64, mask_generator=None, masksper=4, n_estimators=40
):
    """
    Train an ensemble of masked classifiers on tuples of inputs and masks.
    Args:
      Xtrn: N x d inputs
      Ytrn: N array of labels
      nests: int number of estimators
      mask_generator: function that takes in number of random masks to generate.
        If None, then Bernoulli masks are used
      masksper: int number of masks to generate per instance to train each
        classifier
      n_estimators: XGB n_estimators parameter to use for base models
    Returns:
      classifiers: list of nests classifiers
      filters: N x nests array of indicators of which classifiers to use for
        instances (indicating that a classifier was *not* trained on the
        respective instance)
    """

    classifiers = []
    splits_rand = []
    N_tot = Xtrn.shape[0]

    d = Xtrn.shape[1]
    for vi in range(nests):
        print("\n\n\n\n##########\nrand split {}\n##########\n\n\n\n".format(vi))
        # Get random split
        in_range = np.random.rand(N_tot) <= 0.5
        splits_rand.append(in_range)
        X_class = Xtrn[in_range]
        Y_class = Ytrn[in_range]
        # Make masks
        X_class = np.concatenate([X_class] * masksper, 0)
        Y_class = np.concatenate([Y_class] * masksper, 0)
        if mask_generator is None:
            B = np.concatenate(
                [
                    np.sum(
                        np.random.permutation(np.eye(d))[:, : np.random.randint(d)],
                        1,
                        keepdims=True,
                    )
                    for _ in range(X_class.shape[0])
                ],
                1,
            )
            B = np.float32(B.T)
        else:
            B = mask_generator(X_class.shape[0])
        X_class = np.concatenate((X_class * B, B), 1)
        # Train classifier
        est = XGBClassifier(n_estimators=40)
        est.fit(X_class, Y_class)
        classifiers.append(est)

    return classifiers, np.logical_not(np.stack(splits_rand, -1))


# train initial classifier
init_classifiers, init_filters = train_classifiers(
    Xtrn, Ytrn, nests=64, masksper=4, n_estimators=40
)

"""Since we need to begin with *an* acquisition, all templates should share a common feature.

There are several potential ways of estimating what this starting feature should be. Here, I propose using the [ACO cost objective](https://proceedings.mlr.press/v235/valancius24a.html):
$\arg\min_{v \subseteq \{1, \dots, d\} \setminus o} \mathbb{E}_{\mathbf{y}, \mathbf{x}_v \mid {x}_o} \left[ \ell \left( \hat{y}({x}_o, \mathbf{x}_v), \mathbf{y} \right) \right] + \alpha c(v; o)$ for the special case where $o = \emptyset$; i.e. $\arg\min_{v \subseteq \{1, \dots, d\} } \mathbb{E}_{\mathbf{y}, \mathbf{x}_v} \left[ \ell \left( \hat{y}(\mathbf{x}_v), \mathbf{y} \right) \right] + \alpha c(v)$, which is equivalent to a static feature selection type loss. Note that this will return an entire subset $v \subseteq [\![d]\!]$. We can perform multiple trials to select a single feature (e.g., based on stability of selection).

`estimate_start` is a helper function to estimate the above cost objective by keeping track of the lowest mask cost objective that each feature appears in (i.e. the total loss of the best mask that contains each feature).
"""


def estimate_start(
    Xtrn, Ytrn, classifier_filters, classifiers, featcost, ntrials=500, trl_bsize=5000
):
    """
    Estimate the lowest mask cost objective that each feature appears in (i.e.
    the cost objective of the best mask that contains each feature).
    Args:
      Xtrn: N x d inputs
      Ytrn: N array of labels
      classifier_filters: N x nests array of indicators of which classifiers to
        use for instances
      classifiers: list of nests classifiers
      featcost: alpha penalty multiplier to l1-norm of masks
      ntrials: number of maskes to consider
      trl_bsize: batch size for to estimate average NLL for each mask
    Returns:
      startdim: a feature in the lowest cost objective mask
      bestmask: d len array of lowest cost objective of the best mask
        that contains each feature
    """
    mval = 1e8
    bestmask = 1e8 * np.ones((d,), dtype=np.float32)
    B = np.concatenate(
        [
            np.sum(
                np.random.permutation(np.eye(d))[:, : np.random.randint(d)],
                1,
                keepdims=True,
            )
            for _ in range(ntrials)
        ],
        1,
    )
    B = np.float32(B.T)
    for trl in range(ntrials):
        print(trl, np.min(bestmask), np.argmin(bestmask))
        rprm = np.random.permutation(Xtrn.shape[0])[:trl_bsize]
        Btrl = np.tile(B[trl, None, :], (len(rprm), 1))
        XBtrl = np.concatenate((Xtrn[rprm] * Btrl, Btrl), 1)
        preds = np.stack([est.predict_proba(XBtrl) for est in classifiers], -1)
        if classifier_filters is None:
            preds = np.mean(preds, -1)
        else:
            nests = np.sum(classifier_filters[rprm], -1, keepdims=True)
            preds = np.sum(preds * classifier_filters[rprm, None, :], -1) / nests

        nlls = np.stack([-np.log(preds[i, y]) for i, y in enumerate(Ytrn[rprm])], 0)
        crit = np.mean(nlls) + featcost * np.sum(B[trl])
        bestmask = np.minimum(bestmask, crit * B[trl] + mval * (1.0 - B[trl]))
    return np.argmin(bestmask), bestmask


"""`estimate_start` is meant to consider relatively few masks and bigger batch sizes for estimating average NLL. `estimate_start_minitrials` considers more masks and smaller batches instead, which can be useful for further tie-breaks."""


def eval_masks(
    X, B, classifiers, Y=None, bsize=16, matched_B=False, classifier_filters=None
):
    """
    Evaluate an ensemble of classifiers on tuples of inputs and masks.
    Args:
      X: N x d data matrix
      B: M x d mask matrix
      Y: N array of labels. If Y is given then the negative log likelihoods
        is returned else predictions are returned.
      If matched_B is True then N==M and instances are only evaluated on
        respective masks; else (default), all instances are evaluated on each
        mask in B.
      classifier_filter: N x nests matrix of indicators of which classifiers to
        use for instances
    Returns: N x M nlls if Y is given else N x M x nclasses predictions (when
      matched_B=False).
    """
    N = X.shape[0]
    M = B.shape[0]

    if Y is not None:
        if matched_B:
            out = np.zeros((N,), np.float32)
        else:
            out = np.zeros((N, M), np.float32)
    else:
        if matched_B:
            out = np.zeros((N, classifiers[0].n_classes_), np.float32)
        else:
            out = np.zeros((N, M, classifiers[0].n_classes_), np.float32)
    for bi in range(0, N, bsize):
        Xbatch = X[bi : bi + bsize]
        Ybatch = Y[bi : bi + bsize]
        if matched_B:
            Bbatch = B[bi : bi + bsize]
        else:
            Bbatch = np.tile(B, (Xbatch.shape[0], 1))
            Xbatch = np.repeat(Xbatch, M, 0)

        Xbatch = np.concatenate((Xbatch * Bbatch, Bbatch), 1)
        preds = np.stack([est.predict_proba(Xbatch) for est in classifiers], -1)
        if classifier_filters is None:
            preds = np.mean(preds, -1)
        else:
            split_batch = classifier_filters[bi : bi + bsize]
            split_batch = np.repeat(split_batch, M, 0)
            nests = np.sum(split_batch, -1, keepdims=True)
            # print(preds.shape)
            # print(split_batch.shape)
            # print(nests.shape)
            preds = np.sum(preds * split_batch[:, None, :], -1) / nests
        if not matched_B:
            preds = preds.reshape(-1, M, classifiers[0].n_classes_)
        if Y is None:
            out[bi : bi + bsize, ...] = preds
        else:
            out[bi : bi + bsize, ...] = np.stack(
                [-np.log(preds[i, ..., y]) for i, y in enumerate(Ybatch)], 0
            )
    return out


def estimate_start_minitrials(
    Xtrn, Ytrn, classifier_filters, classifiers, featcost, ntrials=32, trl_bsize=64
):
    bestmask = np.zeros((d,), dtype=np.float32)

    for trl in range(ntrials):
        print(trl)
        rprm = np.random.permutation(Xtrn.shape[0])[:trl_bsize]
        B = np.concatenate(
            [
                np.sum(
                    np.random.permutation(np.eye(d))[:, : np.random.randint(d)],
                    1,
                    keepdims=True,
                )
                for _ in range(5000)
            ],
            1,
        )
        B = np.float32(B.T)
        nlls = eval_masks(
            Xtrn[rprm],
            B,
            classifiers,
            Y=Ytrn[rprm],
            classifier_filters=classifier_filters[rprm],
        )
        crit = np.mean(nlls, 0) + featcost * np.sum(B, 1)
        trlbest = B[np.argmin(crit), :]
        print(trlbest)
        bestmask = bestmask + trlbest
    return np.argmax(bestmask), bestmask


# %%
# config
featcost = 0.075

_, bestmask1 = estimate_start(Xtrn, Ytrn, init_filters, init_classifiers, featcost)
_, bestmask2 = estimate_start(Xtrn, Ytrn, init_filters, init_classifiers, featcost)
bestmask = 0.5 * (bestmask1 + bestmask2)
print(bestmask)

# tie-break if needed
if np.sum(np.equal(bestmask, np.min(bestmask))) > 1:
    print("tie!")
    _, bestmask_tiebreak = estimate_start_minitrials(
        Xtrn, Ytrn, init_filters, init_classifiers, featcost
    )
    startdim = np.argmax(bestmask_tiebreak * np.equal(bestmask, np.min(bestmask)))
    plt.plot(bestmask_tiebreak * np.equal(bestmask, np.min(bestmask)))
else:
    startdim = np.argmin(bestmask)
    plt.plot(bestmask)

startdim

# %%
"""Now that we have the common feature (the starting feature in AFA), we can look for our 'templates'.

Since the space of potential masks is huge, $2^d$, it's prudent to precompute and cache mask cost objectives on a set of potential mask candidates. `eval_masks` and `get_mask_losses` are helper functions to do so.
"""


def get_mask_losses(
    Xtrn, Ytrn, B, classifiers, featcost, bsize=256, classifier_filters=None
):
    # TODO: use filters?
    mask_costs = featcost * np.sum(B, 1)

    bsize = 256
    Xcosts = []
    for si in range(0, Xtrn.shape[0], bsize):
        print(si)
        if classifier_filters is not None:
            nlls = eval_masks(
                Xtrn[si : si + bsize],
                B,
                classifiers,
                Y=Ytrn[si : si + bsize],
                classifier_filters=classifier_filters[si : si + bsize],
            )
        else:
            nlls = eval_masks(
                Xtrn[si : si + bsize], B, classifiers, Y=Ytrn[si : si + bsize]
            )
        Xcosts.append(nlls + mask_costs)

    return np.concatenate(Xcosts, 0)


"""Let $\mathcal{M}$ be the universe of masks, and $c^{(i)}_j$ be the cost of the $j$th mask on the $i$th instance. We can then pose the template finding problem as finding  $$\hat{T} = \operatorname{argmin}\limits_{T \subset \mathcal{M},\, |T|=K} \frac{1}{N}\sum_{i=1}^N \min_{j\in T} c^{(i)}_j.$$

Clearly, one can employ a greedy strategy to add a single additional mask to a current template set $T$. I propose an adjusted cost approach to each greedy iteration for easy vectorization.
"""


def vanilla_greedy_cost_selection(costs, k, selected=None):
    # Start selected set with the mask that gives to lowest avg cost
    if selected is None:
        selected = [np.argmax(np.mean(costs, 0))]
    for i in range(1, k):
        # best possible cost for each instance with current set of masks
        selected_cost = np.min(costs[:, selected], -1, keepdims=True)
        print("{} {}".format(i, np.mean(selected_cost)))
        # potential improvement to each instances if respective mask were available
        adj_cost = np.minimum(costs - selected_cost, 0)  # measuring savings over best
        mean_adj_cost = np.mean(adj_cost, 0)
        if not np.any(mean_adj_cost < 0.0):
            return selected
        selected.append(np.argmin(mean_adj_cost))
    return selected


"""Regardless of the template searching routine, we are: 1) considering a limited number of candidates, and 2) considering pre-specified classifiers not tuned to the eventually chosen masks.

I propose to rectify this with a multi-round approach where subsequent rounds refine the candiate set and the classifiers based on
the previously chosen masks.
"""


def gen_randmaks(B_filter, startdim, nrand):
    # Generate according to size and marginal feature distribution in B_filter
    Brands = []
    d = B_filter.shape[1]
    eyed = np.eye(d, dtype=np.float32)
    sizep = np.mean(eyed[np.int32(np.sum(B_filter, 1)) - 1, :], 0)
    featp = np.mean(B_filter, 0)
    featp = featp * (1.0 - eyed[startdim, :])
    featp = featp / np.sum(featp)
    dints = np.arange(d)
    for _ in range(nrand):
        nfeats = np.random.choice(dints, size=1, replace=False, p=sizep)[0]
        feats = np.random.choice(dints, size=nfeats, replace=False, p=featp)
        b = eyed[startdim, :] + np.sum(eyed[feats], 0)
        Brands.append(b)
    return np.stack(Brands, 0)


def augment_candidates(B_filter, startdim, nrand):
    # Augment candidates by removing features from current set and randomly
    # generating according to feature distribution
    d = B_filter.shape[1]
    eyed = np.eye(d, dtype=np.float32)
    estart = eyed[startdim]
    # consider new candidates by removing one feature from masks
    Bs = []
    for b in B_filter:
        for j in np.flatnonzero(b - estart):
            Bs.append(b - eyed[j])
    B = np.stack(Bs, 0)
    B = np.concatenate([B, B_filter], 0)
    B = np.unique(B, axis=0)

    # consider new candidate by generating according to marginal feature distro
    Brands = gen_randmaks(B_filter, startdim, nrand)
    B = np.concatenate([B, Brands], 0)
    B = np.unique(B, axis=0)
    return B


def find_templates(
    Xtrn,
    Ytrn,
    startdim,
    init_classifiers,
    init_filters,
    nselect,
    featcost,
    ncand=10000,
    nrounds=3,
    nsubsamp=None,
    cost_selection=vanilla_greedy_cost_selection,
    Xeval=None,
    Yeval=None,
):
    classifiers = init_classifiers
    filters = init_filters
    d = Xtrn.shape[1]
    eyed = np.eye(d, dtype=np.float32)
    estart = eyed[startdim]

    eval_costss = []

    # get initial templates
    B = np.concatenate(
        [
            np.sum(
                np.random.permutation(eyed)[:, : np.random.randint(d)], 1, keepdims=True
            )
            for _ in range(ncand)
        ],
        1,
    )
    B = np.float32(B.T)
    B[:, startdim] = 1.0
    mask_costs = featcost * np.sum(B, 1)
    for ri in range(nrounds):
        print(ri)

        ## subsample point for speed
        if nsubsamp is not None:
            rprm = np.random.permutation(Xtrn.shape[0])[:nsubsamp]
            Xrnd = Xtrn[rprm]
            Yrnd = Ytrn[rprm]
        else:
            Xrnd = Xtrn
            Yrnd = Ytrn

        # nests = 4 if ri == 0 else len(init_classifiers)
        # TODO: use the filters to get held out predictions?
        if ri == 0:
            # Since this is first round, do something quick and dirty
            Xcosts = get_mask_losses(
                Xrnd, Yrnd, B, classifiers[:4], featcost, bsize=256
            )
        else:
            Xcosts = get_mask_losses(
                Xrnd,
                Yrnd,
                B,
                classifiers,
                featcost,
                bsize=256,
                classifier_filters=filters if nsubsamp is None else filters[rprm],
            )

        selected = cost_selection(Xcosts, nselect)
        B_templates = B[selected, :]
        B = augment_candidates(B_templates, startdim, 2 * len(B_templates))

        if Yeval is not None:
            Xcosts_eval = get_mask_losses(
                Xeval, Yeval, B_templates, classifiers, featcost, bsize=256
            )
            pretune_costs = np.mean(np.min(Xcosts_eval, -1))

        classifiers, filters = train_classifiers(
            Xtrn,
            Ytrn,
            nests=len(init_classifiers),
            mask_generator=lambda s: gen_randmaks(B_templates, startdim, s),
            masksper=4,
            n_estimators=40,
        )

        if Yeval is not None:
            Xcosts_eval = get_mask_losses(
                Xeval, Yeval, B_templates, classifiers, featcost, bsize=256
            )
            posttune_costs = np.mean(np.min(Xcosts_eval, -1))
            print(pretune_costs, posttune_costs)
            eval_costss.append((pretune_costs, posttune_costs))

    if Yeval is not None:
        return B_templates, classifiers, filters, eval_costss
    return B_templates, classifiers, filters


# %%
# get templates
rprm = np.random.permutation(Xval.shape[0])[:1500]
Xeval = Xval[rprm]
Yeval = Yval[rprm]
B_temp, classifiers, filters, eval_costs = find_templates(
    Xtrn,
    Ytrn,
    startdim,
    init_classifiers,
    init_filters,
    nselect=128,
    featcost=featcost,
    ncand=10000,
    nrounds=3,
    nsubsamp=2**13,
    Xeval=Xeval,
    Yeval=Yeval,
)

eval_costs


# %%
"""Roll out"""


# def tf_arbitrary_knn(Xtrn, Ytrn, Xtst, indices, k=1, Xtrnl2=None, toss_first=False):
#     """
#     Args:
#       Xtrn: N x d Train Instances
#       Ytrn: N x nclass Train Labels (e.g., one-hot)
#       Xtst: M x d Query Instances
#       indices: list of features to use
#       k: number of neighbors
#       Xtrnl2: N x 1 vector of squared norms of Xtrn instances
#       toss_first: flag to throwout the first neighbor
#                   (if querying within training set)
#     """
#     Xtrnfeats = tf.gather(Xtrn, indices, axis=1)
#     Xtstfeats = tf.gather(Xtst, indices, axis=1)
#     if Xtrnl2 is None:
#         Xtrnl2 = tf.reduce_sum(Xtrnfeats**2, axis=1, keepdims=True)
#     d2 = (
#         Xtrnl2
#         - 2.0 * tf.matmul(Xtrnfeats, Xtstfeats, transpose_b=True)
#         + tf.transpose(tf.reduce_sum(Xtstfeats**2, axis=1, keepdims=True))
#     )
#     d2_sorti = tf.argsort(d2, axis=0)
#     Y_neighbors = tf.reduce_mean(
#         tf.gather(
#             Ytrn,
#             tf.transpose(
#                 d2_sorti[(1 if toss_first else 0) : (k + 1 if toss_first else k), :]
#             ),
#             axis=0,
#         ),
#         axis=1,
#     )
#     return Y_neighbors


def tf_arbitrary_knn(Xtrn, Ytrn, Xtst, indices, k=1, Xtrnl2=None, toss_first=False):
    """
    Args:
      Xtrn: N x d Train Instances
      Ytrn: N x nclass Train Labels (e.g., one-hot)
      Xtst: M x d Query Instances
      indices: list of features to use
      k: number of neighbors
      Xtrnl2: N x 1 vector of squared norms of Xtrn instances
      toss_first: flag to throwout the first neighbor
                  (if querying within training set)
    """
    import torch as th

    # Xtrnfeats = np.take_along_axis(Xtrn, indices, axis=1)
    # Xtstfeats = np.take_along_axis(Xtst, indices, axis=1)
    Xtrnfeats = Xtrn[:, indices]
    Xtstfeats = Xtst[:, indices]
    if Xtrnl2 is None:
        Xtrnl2 = np.sum(Xtrnfeats**2, axis=1, keepdims=True)
    d2 = (
        Xtrnl2
        - 2.0 * np.matmul(Xtrnfeats, Xtstfeats.T)
        + np.transpose(np.sum(Xtstfeats**2, axis=1, keepdims=True))
    )
    d2_sorti = np.argsort(d2, axis=0)
    ntmpl: int = Ytrn.shape[1]
    n: int = d2_sorti.shape[1]
    d2_sorti = th.as_tensor(d2_sorti)[:, None, :].expand(-1, ntmpl, -1).numpy()
    ys = th.as_tensor(Ytrn)[:, :, None].expand(-1, -1, n).numpy()
    Y_neighbors = np.mean(
        np.take_along_axis(
            ys,
            d2_sorti[(1 if toss_first else 0) : (k + 1 if toss_first else k), :, :],
            axis=0,
        ),
        axis=0,
    ).T
    return Y_neighbors


class ClassifierBank:
    def __init__(self, nests, X, Y):
        self.ests = {}
        self.lastused = []
        self.nests = nests
        self.Xtrn = X
        self.Ytrn = Y

    def get_estimator(self, b):
        # bstr = '{}'.format(b)
        bstr = np.array2string(b, max_line_width=np.inf)
        if bstr in self.ests:
            print("Found {}".format(bstr))
            self.lastused.remove(bstr)
            est = self.ests[bstr]
        else:
            print("\tTraining {}".format(bstr))
            est = XGBClassifier(n_estimators=40)
            est.fit(self.Xtrn[:, b > 0], self.Ytrn)
            print("\tTrained {}".format(bstr))
            self.ests[bstr] = est

        self.lastused.insert(0, bstr)

        if len(self.lastused) > self.nests:
            stale = self.lastused.pop()
            del self.ests[stale]
        return est


def eval_rollout(
    Xval,
    Yval,
    startdim,
    featcost,
    Xtrn,
    Ytrn,
    tempNLLtrn,
    B_temp,
    ao_k=5,
    bank=None,
    classifiers=None,
):
    d = Xval.shape[1]
    eyed = np.eye(d, dtype=np.float32)
    eyedplusone = np.eye(d + 1, dtype=np.float32)

    accu_ao = []
    bs_ao = []
    # ao_k = 5
    for i in range(Xval.shape[0]):
        print("\n\n\n{}".format(i))
        # i = np.random.randint(Xval.shape[0])
        for s in range(d + 1):
            if s == 0:
                # if in the first step, draw action from null_distribution
                # b_curr = np.float32(np.random.multinomial(1, p_null))
                b_curr = eyed[startdim, None, :]  # Deterministic start
                print(b_curr)
                continue  # move to next step
            elif s < d:
                xo = Xval[i, None, :] * b_curr

                nllroll = tf_arbitrary_knn(
                    Xtrn, tempNLLtrn, xo, np.flatnonzero(b_curr[0]), k=ao_k
                )

                mask_needed = np.maximum(
                    B_temp - b_curr, 0.0
                )  # fine if we have additional feats
                mask_costs = featcost * np.sum(mask_needed, 1)
                classifier_costs = nllroll + mask_costs
                best_clss = np.argmin(classifier_costs)
                # print('>>{}'.format(np.sort(classifier_costs)))
                # print('>>{}'.format(mask_needed[best_clss, :]))
                a_pred = np.concatenate(
                    [mask_needed[best_clss, :], [0.0]]
                )  # TODO: tie break with softmax combination?
                # a_pred[:-1] = a_pred[:-1] - 1e8*b_curr[0]  # Don't acquire what's already acquired
                a_pred[:-1] = a_pred[:-1] * (1.0 - b_curr[0])
                if np.sum(a_pred[:-1]) == 0.0:
                    a_pred[-1] = 1.0
                else:
                    a_pred[:-1] = a_pred[:-1] / np.sum(a_pred[:-1])
                    a_pred[:-1] = a_pred[:-1] * (1.0 - a_pred[-1])
                action = eyedplusone[:, np.argmax(a_pred)]  # TODO: case with ties?
                # a_pred = le.inverse_transform(
                #   policy.predict_proba(np.concatenate((xo, b_curr), -1))[0, :])
                # action = eyedplusone[:, np.argmax(a_pred)]
                if action[-1] == 0.0:  # not predicting
                    b_curr = b_curr + action[:-1]
                    print(b_curr)
                    continue  # move to next step
            # make prediction
            print(np.flatnonzero(b_curr[0]))
            if bank is not None:
                est = bank.get_estimator(b_curr[0])
                y_pred = est.predict_proba(Xval[i : i + 1, b_curr[0] > 0])
            elif classifiers is not None:
                y_pred = np.mean(
                    np.stack(
                        [
                            est.predict_proba(np.concatenate((xo, b_curr), 1))
                            for est in classifiers
                        ],
                        -1,
                    ),
                    -1,
                )
            else:
                est = XGBClassifier(n_estimators=40)
                est.fit(Xtrn[:, b_curr[0] > 0], Ytrn)
                y_pred = est.predict_proba(Xval[i : i + 1, b_curr[0] > 0])

            print(y_pred, np.argmax(y_pred[0, :]), int(Yval[i]))
            accu_ao.append(np.argmax(y_pred[0, :]) == int(Yval[i]))
            print("correct!") if accu_ao[-1] else print("wrong!")
            bs_ao.append(b_curr)
            print(np.mean(accu_ao))
            print(np.mean([np.sum(b) for b in bs_ao]))
            break
    return np.mean(accu_ao), np.mean([np.sum(b) for b in bs_ao])


# %%
print(Xtrn.shape)
print(Ytrn.shape)
print(filters.shape)

Xcoststrn = get_mask_losses(
    Xtrn, Ytrn, B_temp, classifiers, 0.0, bsize=256, classifier_filters=filters
)

# %%
"""Roll out with personalized bank of classifiers as $\hat{y}$."""

cbank = ClassifierBank(1000, Xtrn, Ytrn)

# %%
o1, o2 = eval_rollout(
    Xval, Yval, startdim, featcost, Xtrn, Ytrn, Xcoststrn, B_temp, bank=cbank
)

# %%
o1, o2 = eval_rollout(
    Xval, Yval, startdim, featcost, Xtrn, Ytrn, Xcoststrn, B_temp, bank=cbank, ao_k=10
)

# %%
o1, o2 = eval_rollout(
    Xval, Yval, startdim, featcost, Xtrn, Ytrn, Xcoststrn, B_temp, bank=cbank, ao_k=20
)

# %%
"""Roll out with ensemble of classifiers for $\hat{y}$."""

o1, o2 = eval_rollout(
    Xval,
    Yval,
    startdim,
    featcost,
    Xtrn,
    Ytrn,
    Xcoststrn,
    B_temp,
    classifiers=classifiers,
)

o1, o2 = eval_rollout(
    Xval,
    Yval,
    startdim,
    featcost,
    Xtrn,
    Ytrn,
    Xcoststrn,
    B_temp,
    classifiers=classifiers,
    ao_k=20,
)
